services:
  postgres:
    image: postgres:latest
    container_name: telegram-dashboard
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telegram-dashboard
    ports:
      - "5001:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
